"""
Infrared proxy management module.

Generates Infrared config files from the database. Infrared is a Go-based
connection-level Minecraft reverse proxy (github.com/haveachin/infrared) that
routes by the hostname in the client's handshake packet. Unlike Velocity, it
requires no backend plugin/config — backends run with their own online-mode=true.

Infrared runs in a separate Docker container (mc-infrared). This module writes
the config files to the shared volume; Infrared watches the proxies directory
and hot-reloads when files change, so no container restart is needed.

Layout inside the mounted volume (./data/infrared → /etc/infrared):
  config.yml              — global Infrared settings (bind, timeouts, filters)
  proxies/<name>.yml      — one file per Minecraft server, defines domain→backend
"""

import os
import docker

from api.db import get_all_servers, get_server_port_from_properties

# Paths (relative to project root when running inside management container)
INFRARED_DIR = os.path.abspath("data/infrared")
CONFIG_YML = os.path.join(INFRARED_DIR, "config.yml")
PROXIES_DIR = os.path.join(INFRARED_DIR, "proxies")

# Compose service name of the Infrared proxy (see docker-compose*.yml).
INFRARED_SERVICE_NAME = "infrared"
# Legacy fixed container name, used only as a last-resort fallback.
INFRARED_CONTAINER_NAME = "mc-infrared"


def get_infrared_container(client=None):
    """
    Locate the Infrared proxy container.

    Resolution order:
      1. ``INFRARED_CONTAINER`` env var (explicit container name/id)
      2. the ``infrared`` service of our own compose project (by labels —
         works under Coolify, which rewrites ``container_name``)
      3. the legacy fixed name ``mc-infrared``

    Raises ``docker.errors.NotFound`` when nothing matches.
    """
    from api.post.server.mounts import find_sibling_container

    client = client or docker.from_env()
    explicit = os.environ.get("INFRARED_CONTAINER", "").strip()
    if explicit:
        return client.containers.get(explicit)
    sibling = find_sibling_container(INFRARED_SERVICE_NAME, client=client)
    if sibling is not None:
        return sibling
    return client.containers.get(INFRARED_CONTAINER_NAME)

# Bind address for Infrared
INFRARED_BIND = "0.0.0.0:25565"

# Container label set by run.py on server containers whose image ships the
# go-mmproxy real-IP helper. Its value is the port go-mmproxy listens on;
# Infrared then targets that port and sends the PROXY protocol header.
REAL_IP_LABEL = "mc.real-ip.port"


def get_real_ip_port(container_name, client=None):
    """
    Return the go-mmproxy port for ``container_name`` if the container was
    started with the real-IP helper, else None (route directly to the
    server port without a PROXY header). Works for stopped containers too.
    """
    try:
        client = client or docker.from_env()
        container = client.containers.get(container_name)
        value = (container.labels or {}).get(REAL_IP_LABEL)
        return int(value) if value else None
    except Exception:
        return None


def ensure_infrared_dirs():
    """Create the Infrared config directories if they don't exist."""
    os.makedirs(INFRARED_DIR, exist_ok=True)
    os.makedirs(PROXIES_DIR, exist_ok=True)


def generate_infrared_config():
    """
    Write the top-level config.yml with bind address and sensible defaults.

    This is idempotent — safe to call on every startup and config reload.
    """
    ensure_infrared_dirs()

    config_content = f"""# Infrared configuration — auto-generated by MinecraftServerTool
# Do NOT edit manually; changes will be overwritten.

bind: {INFRARED_BIND}

keepAliveTimeout: 30s

proxyProtocol:
  receive: false
  trustedCIDRs:
    - 127.0.0.1/32

filters:
  rateLimiter:
    requestLimit: 10
    windowLength: 1s
"""

    with open(CONFIG_YML, "w") as f:
        f.write(config_content)

    print(f"[Infrared] Global config written to {CONFIG_YML}")


def generate_proxy_files():
    """
    Write one YAML file per server into the proxies/ directory.

    Each server with a hostname gets a routing rule. Servers without a
    hostname are skipped (they would collide on the wildcard). Any stale
    files for servers that no longer exist are removed.
    """
    ensure_infrared_dirs()
    servers = get_all_servers()

    current_names = set()
    written = 0
    try:
        client = docker.from_env()
    except Exception:
        client = None

    for srv in servers:
        name = srv["name"]
        container_name = srv.get("container_name") or f"mc-{name}"
        port = get_server_port_from_properties(name)
        hostname = srv.get("hostname")

        if not hostname:
            print(f"[Infrared] Skipping server '{name}' (no hostname configured).")
            continue

        current_names.add(f"{name}.yml")

        # Real player IPs: if the container runs go-mmproxy, hand the
        # connection to it with a PROXY protocol header. Otherwise connect
        # straight to the server port (no header — the server would choke).
        real_ip_port = get_real_ip_port(container_name, client) if client else None
        if real_ip_port:
            backend = f"{container_name}:{real_ip_port}"
            extra = "\n# Forward the player's real address (consumed by go-mmproxy in the container).\nsendProxyProtocol: true\n"
        else:
            backend = f"{container_name}:{port}"
            extra = ""

        proxy_content = f"""# Infrared proxy for server '{name}' — auto-generated.
domains:
  - "{hostname}"

addresses:
  - {backend}
{extra}"""
        proxy_path = os.path.join(PROXIES_DIR, f"{name}.yml")
        with open(proxy_path, "w") as f:
            f.write(proxy_content)
        written += 1

    if written == 0:
        placeholder_content = """# Infrared placeholder proxy to prevent container crash when no servers exist yet.
domains:
  - "placeholder.invalid"

addresses:
  - "localhost:25565"
"""
        placeholder_path = os.path.join(PROXIES_DIR, "placeholder.yml")
        with open(placeholder_path, "w") as f:
            f.write(placeholder_content)
        current_names.add("placeholder.yml")
        print("[Infrared] Written placeholder proxy file to prevent startup crash.")

    # Remove stale proxy files for deleted servers
    if os.path.isdir(PROXIES_DIR):
        for fname in os.listdir(PROXIES_DIR):
            if fname.endswith(".yml") and fname not in current_names:
                stale_path = os.path.join(PROXIES_DIR, fname)
                try:
                    os.remove(stale_path)
                    print(f"[Infrared] Removed stale proxy file: {fname}")
                except OSError as e:
                    print(f"[Infrared] Failed to remove stale file {fname}: {e}")

    print(f"[Infrared] {written} proxy file(s) written.")


def reload_proxy_config():
    """
    Regenerate Infrared's config files from the database and restart the proxy container
    to apply the changes, since Infrared does not support dynamic hot-reloading.
    """
    generate_infrared_config()
    generate_proxy_files()

    # Restart the proxy container to force reload of the configurations.
    try:
        client = docker.from_env()
        container = get_infrared_container(client)
        if container.status == "running":
            print(f"[Infrared] Restarting '{container.name}' to apply configuration changes...")
            container.restart(timeout=1)
            print(f"[Infrared] Container '{container.name}' restarted successfully.")
        else:
            print(f"[Infrared] Container '{container.name}' is {container.status}; "
                  "config will apply when it starts.")
        return True
    except docker.errors.NotFound:
        print("[Infrared] Proxy container not found. "
              "It will pick up the config when it starts.")
        return False
    except Exception as e:
        print(f"[Infrared] Warning: could not restart proxy container: {e}")
        return False
