"""
Infrared proxy management module.

Generates Infrared config files from the database. Infrared is a Go-based
connection-level Minecraft reverse proxy (github.com/haveachin/infrared) that
routes by the hostname in the client's handshake packet. Unlike Velocity, it
requires no backend plugin/config — backends run with their own online-mode=true.

Infrared runs in a separate Docker container (mc-infrared). This module writes
the config files to the shared volume; Infrared watches the proxies directory
and hot-reloads when files change, so no container restart is needed.

Layout inside the mounted volume (./data/infrared → /etc/infrared):
  config.yml              — global Infrared settings (bind, timeouts, filters)
  proxies/<name>.yml      — one file per Minecraft server, defines domain→backend
"""

import os
import docker

from api.db import get_all_servers

# Paths (relative to project root when running inside management container)
INFRARED_DIR = os.path.abspath("data/infrared")
CONFIG_YML = os.path.join(INFRARED_DIR, "config.yml")
PROXIES_DIR = os.path.join(INFRARED_DIR, "proxies")

# Name of the Infrared Docker container (must match docker-compose.yml)
INFRARED_CONTAINER_NAME = "mc-infrared"

# Bind address for Infrared
INFRARED_BIND = "0.0.0.0:25565"


def ensure_infrared_dirs():
    """Create the Infrared config directories if they don't exist."""
    os.makedirs(INFRARED_DIR, exist_ok=True)
    os.makedirs(PROXIES_DIR, exist_ok=True)


def generate_infrared_config():
    """
    Write the top-level config.yml with bind address and sensible defaults.

    This is idempotent — safe to call on every startup and config reload.
    """
    ensure_infrared_dirs()

    config_content = f"""# Infrared configuration — auto-generated by MinecraftServerTool
# Do NOT edit manually; changes will be overwritten.

bind: {INFRARED_BIND}

keepAliveTimeout: 30s

proxyProtocol:
  receive: false
  trustedCIDRs:
    - 127.0.0.1/32

filters:
  rateLimiter:
    requestLimit: 10
    windowLength: 1s
"""

    with open(CONFIG_YML, "w") as f:
        f.write(config_content)

    print(f"[Infrared] Global config written to {CONFIG_YML}")


def generate_proxy_files():
    """
    Write one YAML file per server into the proxies/ directory.

    Each server with a hostname gets a routing rule. Servers without a
    hostname are skipped (they would collide on the wildcard). Any stale
    files for servers that no longer exist are removed.
    """
    ensure_infrared_dirs()
    servers = get_all_servers()

    current_names = set()
    written = 0

    for srv in servers:
        name = srv["name"]
        container_name = srv.get("container_name") or f"mc-{name}"
        port = srv.get("port") or 25565
        hostname = srv.get("hostname")

        if not hostname:
            print(f"[Infrared] Skipping server '{name}' (no hostname configured).")
            continue

        current_names.add(f"{name}.yml")

        proxy_content = f"""# Infrared proxy for server '{name}' — auto-generated.
domains:
  - "{hostname}"

addresses:
  - {container_name}:{port}
"""
        proxy_path = os.path.join(PROXIES_DIR, f"{name}.yml")
        with open(proxy_path, "w") as f:
            f.write(proxy_content)
        written += 1

    # Remove stale proxy files for deleted servers
    if os.path.isdir(PROXIES_DIR):
        for fname in os.listdir(PROXIES_DIR):
            if fname.endswith(".yml") and fname not in current_names:
                stale_path = os.path.join(PROXIES_DIR, fname)
                try:
                    os.remove(stale_path)
                    print(f"[Infrared] Removed stale proxy file: {fname}")
                except OSError as e:
                    print(f"[Infrared] Failed to remove stale file {fname}: {e}")

    print(f"[Infrared] {written} proxy file(s) written.")


def reload_proxy_config():
    """
    Regenerate Infrared's config files from the database.

    Infrared watches the proxies directory and hot-reloads automatically when
    files change, so no container restart is needed in the happy path. If the
    container is missing we silently skip — it will pick up the config when
    it starts.
    """
    generate_infrared_config()
    generate_proxy_files()

    # Best-effort sanity check that the container is alive.
    try:
        client = docker.from_env()
        container = client.containers.get(INFRARED_CONTAINER_NAME)
        if container.status != "running":
            print(f"[Infrared] Container '{INFRARED_CONTAINER_NAME}' is {container.status}; "
                  "config will apply when it starts.")
        else:
            print(f"[Infrared] Config updated; Infrared will hot-reload.")
        return True
    except docker.errors.NotFound:
        print(f"[Infrared] Container '{INFRARED_CONTAINER_NAME}' not found. "
              "It will pick up the config when it starts.")
        return False
    except Exception as e:
        print(f"[Infrared] Warning: could not check container status: {e}")
        return False
