"""
Velocity proxy management module.

Handles downloading the Velocity JAR, generating velocity.toml from the database,
and restarting the Velocity process when the configuration changes.
"""

import os
import subprocess
import signal
import json
import requests
import time

from api.db import get_all_servers

# Paths (relative to project root when running inside management container)
VELOCITY_DIR = os.path.abspath("data/velocity")
VELOCITY_JAR = os.path.join(VELOCITY_DIR, "velocity.jar")
VELOCITY_TOML = os.path.join(VELOCITY_DIR, "velocity.toml")
VELOCITY_FORWARDING_SECRET = os.path.join(VELOCITY_DIR, "forwarding.secret")
VELOCITY_PID_FILE = os.path.join(VELOCITY_DIR, "velocity.pid")

# Velocity download URL (latest stable from PaperMC)
VELOCITY_API_URL = "https://api.papermc.io/v2/projects/velocity"

# Default bind address for Velocity
VELOCITY_BIND = "0.0.0.0:25565"


def ensure_velocity_dir():
    """Create the Velocity directory if it doesn't exist."""
    os.makedirs(VELOCITY_DIR, exist_ok=True)


def get_latest_velocity_build():
    """Get the latest Velocity version and build number from PaperMC API."""
    try:
        # Get latest version group
        resp = requests.get(VELOCITY_API_URL, timeout=10)
        resp.raise_for_status()
        versions = resp.json().get("versions", [])
        if not versions:
            return None, None
        latest_version = versions[-1]

        # Get latest build for that version
        builds_url = f"{VELOCITY_API_URL}/versions/{latest_version}/builds"
        resp = requests.get(builds_url, timeout=10)
        resp.raise_for_status()
        builds = resp.json().get("builds", [])
        if not builds:
            return latest_version, None
        latest_build = builds[-1]
        return latest_version, latest_build["build"]
    except Exception as e:
        print(f"[Velocity] Error fetching latest build: {e}")
        return None, None


def download_velocity():
    """Download the Velocity proxy JAR if not already present."""
    ensure_velocity_dir()

    if os.path.exists(VELOCITY_JAR):
        print("[Velocity] velocity.jar already exists, skipping download.")
        return True

    print("[Velocity] Downloading Velocity proxy...")
    version, build = get_latest_velocity_build()
    if not version or not build:
        print("[Velocity] Could not determine latest Velocity version.")
        return False

    download_url = (
        f"{VELOCITY_API_URL}/versions/{version}/builds/{build}/downloads/"
        f"velocity-{version}-{build}.jar"
    )

    try:
        resp = requests.get(download_url, stream=True, timeout=60)
        resp.raise_for_status()
        with open(VELOCITY_JAR, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"[Velocity] Downloaded Velocity {version} (build {build}).")
        return True
    except Exception as e:
        print(f"[Velocity] Download failed: {e}")
        return False


def generate_velocity_toml():
    """
    Generate velocity.toml from the servers in the database.
    
    Each server gets an entry in [servers] and optionally in [forced-hosts]
    if a hostname is configured.
    """
    ensure_velocity_dir()
    servers = get_all_servers()

    # Build server entries: name -> "container_name:port"
    server_entries = []
    forced_host_entries = []
    server_order = []

    for srv in servers:
        name = srv["name"]
        container_name = srv.get("container_name") or f"mc-{name}"
        port = srv.get("port") or 25565
        hostname = srv.get("hostname")

        server_entries.append(f'  {name} = "{container_name}:{port}"')
        server_order.append(f'"{name}"')

        if hostname:
            forced_host_entries.append(f'  "{hostname}" = ["{name}"]')

    # Determine the first server as the default (try list)
    try_list = ", ".join(server_order) if server_order else ""

    # Generate a shared forwarding secret for velocity.toml
    # Each server has its own secret stored in DB, but Velocity uses one global secret
    # We write to forwarding.secret file
    if servers:
        # Use the first server's secret as the global one (or generate one)
        global_secret = servers[0].get("forwarding_secret", "")
        if not global_secret:
            from api.db import generate_forwarding_secret
            global_secret = generate_forwarding_secret()
    else:
        from api.db import generate_forwarding_secret
        global_secret = generate_forwarding_secret()

    # Write forwarding.secret
    with open(VELOCITY_FORWARDING_SECRET, "w") as f:
        f.write(global_secret)

    toml_content = f"""# Velocity configuration — auto-generated by MinecraftServerTool
# Do NOT edit manually; changes will be overwritten.

config-version = "2.7"
bind = "{VELOCITY_BIND}"
motd = "<aqua>Minecraft Server Network</aqua>"
show-max-players = 100
online-mode = true
force-key-authentication = true
player-info-forwarding-mode = "modern"

[servers]
{chr(10).join(server_entries) if server_entries else '  # No servers configured yet'}

[forced-hosts]
{chr(10).join(forced_host_entries) if forced_host_entries else '  # No forced hosts configured yet'}

[advanced]
  compression-threshold = 256
  compression-level = -1
  login-ratelimit = 3000
  connection-timeout = 5000
  read-timeout = 30000
  haproxy-protocol = false
  tcp-fast-open = false
  bungee-plugin-message-channel = true
  show-ping-requests = false
  failover-on-unexpected-server-disconnect = true
  announce-proxy-commands = true
  log-command-executions = false
  log-player-connections = true

[query]
  enabled = false
  port = 25577
"""

    # Add try list if we have servers
    if try_list:
        toml_content += f"""
try = [{try_list}]
"""

    with open(VELOCITY_TOML, "w") as f:
        f.write(toml_content)

    print(f"[Velocity] Configuration written to {VELOCITY_TOML}")
    print(f"[Velocity] {len(servers)} server(s) configured.")
    return True


def start_velocity():
    """Start the Velocity proxy process in the background."""
    ensure_velocity_dir()

    if not os.path.exists(VELOCITY_JAR):
        print("[Velocity] velocity.jar not found. Run download first.")
        return False

    # Generate config before starting
    generate_velocity_toml()

    # Check if already running
    if os.path.exists(VELOCITY_PID_FILE):
        try:
            with open(VELOCITY_PID_FILE, "r") as f:
                pid = int(f.read().strip())
            os.kill(pid, 0)  # Check if process exists
            print(f"[Velocity] Already running with PID {pid}.")
            return True
        except (ProcessLookupError, ValueError):
            # Stale PID file
            os.remove(VELOCITY_PID_FILE)

    # Start Velocity
    print("[Velocity] Starting Velocity proxy...")
    log_path = os.path.join(VELOCITY_DIR, "velocity.log")

    with open(log_path, "a") as log_file:
        process = subprocess.Popen(
            ["java", "-Xmx512M", "-Xms512M", "-jar", VELOCITY_JAR],
            cwd=VELOCITY_DIR,
            stdout=log_file,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )

    # Write PID
    with open(VELOCITY_PID_FILE, "w") as f:
        f.write(str(process.pid))

    print(f"[Velocity] Started with PID {process.pid}.")
    return True


def stop_velocity():
    """Stop the Velocity proxy process."""
    if not os.path.exists(VELOCITY_PID_FILE):
        print("[Velocity] No PID file found. Velocity may not be running.")
        return False

    try:
        with open(VELOCITY_PID_FILE, "r") as f:
            pid = int(f.read().strip())
        os.kill(pid, signal.SIGTERM)
        print(f"[Velocity] Sent SIGTERM to PID {pid}.")
        # Wait briefly for it to terminate
        time.sleep(2)
        try:
            os.kill(pid, 0)
            # Still running, force kill
            os.kill(pid, signal.SIGKILL)
            print(f"[Velocity] Sent SIGKILL to PID {pid}.")
        except ProcessLookupError:
            pass

        os.remove(VELOCITY_PID_FILE)
        print("[Velocity] Stopped.")
        return True
    except (ProcessLookupError, ValueError) as e:
        print(f"[Velocity] Process not found: {e}")
        if os.path.exists(VELOCITY_PID_FILE):
            os.remove(VELOCITY_PID_FILE)
        return False


def restart_velocity():
    """Restart the Velocity proxy (regenerate config + restart process)."""
    print("[Velocity] Restarting...")
    stop_velocity()
    time.sleep(1)
    return start_velocity()


def reload_velocity_config():
    """
    Regenerate the Velocity config and signal the proxy to reload.
    
    Note: Velocity doesn't support live reload of server entries via SIGHUP.
    A full restart is required for server list changes.
    """
    generate_velocity_toml()
    return restart_velocity()
