"""
Velocity proxy management module.

Handles downloading the Velocity JAR, generating velocity.toml from the database,
and restarting the Velocity container when the configuration changes.

Velocity runs in a separate Docker container (mc-velocity). This module generates
the config files that are shared via volume mount, and restarts the container
via the Docker API when config changes.
"""

import os
import json
import requests
import docker

from api.db import get_all_servers

# Paths (relative to project root when running inside management container)
VELOCITY_DIR = os.path.abspath("data/velocity")
VELOCITY_JAR = os.path.join(VELOCITY_DIR, "velocity.jar")
VELOCITY_TOML = os.path.join(VELOCITY_DIR, "velocity.toml")
VELOCITY_FORWARDING_SECRET = os.path.join(VELOCITY_DIR, "forwarding.secret")

# Velocity download URL (latest stable from PaperMC)
VELOCITY_API_URL = "https://api.papermc.io/v2/projects/velocity"

# Default bind address for Velocity
VELOCITY_BIND = "0.0.0.0:25565"

# Name of the Velocity Docker container (must match docker-compose.yml)
VELOCITY_CONTAINER_NAME = "mc-velocity"


def ensure_velocity_dir():
    """Create the Velocity directory if it doesn't exist."""
    os.makedirs(VELOCITY_DIR, exist_ok=True)


def get_latest_velocity_build():
    """Get the latest Velocity version and build number from PaperMC API."""
    try:
        # Get latest version group
        resp = requests.get(VELOCITY_API_URL, timeout=10)
        resp.raise_for_status()
        versions = resp.json().get("versions", [])
        if not versions:
            return None, None
        latest_version = versions[-1]

        # Get latest build for that version
        builds_url = f"{VELOCITY_API_URL}/versions/{latest_version}/builds"
        resp = requests.get(builds_url, timeout=10)
        resp.raise_for_status()
        builds = resp.json().get("builds", [])
        if not builds:
            return latest_version, None
        latest_build = builds[-1]
        return latest_version, latest_build["build"]
    except Exception as e:
        print(f"[Velocity] Error fetching latest build: {e}")
        return None, None


def download_velocity():
    """Download the Velocity proxy JAR if not already present."""
    ensure_velocity_dir()

    if os.path.exists(VELOCITY_JAR):
        print("[Velocity] velocity.jar already exists, skipping download.")
        return True

    print("[Velocity] Downloading Velocity proxy...")
    version, build = get_latest_velocity_build()
    if not version or not build:
        print("[Velocity] Could not determine latest Velocity version.")
        return False

    download_url = (
        f"{VELOCITY_API_URL}/versions/{version}/builds/{build}/downloads/"
        f"velocity-{version}-{build}.jar"
    )

    try:
        resp = requests.get(download_url, stream=True, timeout=60)
        resp.raise_for_status()
        with open(VELOCITY_JAR, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"[Velocity] Downloaded Velocity {version} (build {build}).")
        return True
    except Exception as e:
        print(f"[Velocity] Download failed: {e}")
        return False


def generate_velocity_toml():
    """
    Generate velocity.toml from the servers in the database.

    Each server gets an entry in [servers] and optionally in [forced-hosts]
    if a hostname is configured.
    """
    ensure_velocity_dir()
    servers = get_all_servers()

    # Build server entries: name -> "container_name:port"
    server_entries = []
    forced_host_entries = []
    server_order = []

    for srv in servers:
        name = srv["name"]
        container_name = srv.get("container_name") or f"mc-{name}"
        port = srv.get("port") or 25565
        hostname = srv.get("hostname")

        server_entries.append(f'  {name} = "{container_name}:{port}"')
        server_order.append(f'"{name}"')

        if hostname:
            forced_host_entries.append(f'  "{hostname}" = ["{name}"]')

    # Determine the first server as the default (try list)
    try_list = ", ".join(server_order) if server_order else ""

    # Generate a shared forwarding secret for velocity.toml
    # Each server has its own secret stored in DB, but Velocity uses one global secret
    # We write to forwarding.secret file
    if servers:
        # Use the first server's secret as the global one (or generate one)
        global_secret = servers[0].get("forwarding_secret", "")
        if not global_secret:
            from api.db import generate_forwarding_secret
            global_secret = generate_forwarding_secret()
    else:
        from api.db import generate_forwarding_secret
        global_secret = generate_forwarding_secret()

    # Write forwarding.secret
    with open(VELOCITY_FORWARDING_SECRET, "w") as f:
        f.write(global_secret)

    toml_content = f"""# Velocity configuration — auto-generated by MinecraftServerTool
# Do NOT edit manually; changes will be overwritten.

config-version = "2.7"
bind = "{VELOCITY_BIND}"
motd = "<aqua>Minecraft Server Network</aqua>"
show-max-players = 100
online-mode = true
force-key-authentication = true
player-info-forwarding-mode = "modern"

[servers]
{chr(10).join(server_entries) if server_entries else '  # No servers configured yet'}

[forced-hosts]
{chr(10).join(forced_host_entries) if forced_host_entries else '  # No forced hosts configured yet'}

[advanced]
  compression-threshold = 256
  compression-level = -1
  login-ratelimit = 3000
  connection-timeout = 5000
  read-timeout = 30000
  haproxy-protocol = false
  tcp-fast-open = false
  bungee-plugin-message-channel = true
  show-ping-requests = false
  failover-on-unexpected-server-disconnect = true
  announce-proxy-commands = true
  log-command-executions = false
  log-player-connections = true

[query]
  enabled = false
  port = 25577
"""

    # Add try list if we have servers
    if try_list:
        toml_content += f"""
try = [{try_list}]
"""

    with open(VELOCITY_TOML, "w") as f:
        f.write(toml_content)

    print(f"[Velocity] Configuration written to {VELOCITY_TOML}")
    print(f"[Velocity] {len(servers)} server(s) configured.")
    return True


def reload_velocity_config():
    """
    Regenerate the Velocity config and restart the Velocity container.

    The config is written to the shared volume, then the mc-velocity container
    is restarted via the Docker API so it picks up the new config.
    """
    generate_velocity_toml()

    try:
        client = docker.from_env()
        container = client.containers.get(VELOCITY_CONTAINER_NAME)
        print(f"[Velocity] Restarting container '{VELOCITY_CONTAINER_NAME}'...")
        container.restart(timeout=10)
        print(f"[Velocity] Container restarted.")
        return True
    except docker.errors.NotFound:
        print(f"[Velocity] Container '{VELOCITY_CONTAINER_NAME}' not found. "
              "It will pick up the config when it starts.")
        return False
    except Exception as e:
        print(f"[Velocity] Error restarting container: {e}")
        return False
